name = "post-to-mastodon"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "PlatformTags"
id = "93701dd2179e4a4e958912a19bc55e3e"

[triggers]
crons = ["*/10 * * * *"]